//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vue_Echarts.Dal
{
    using System;
    using System.Collections.Generic;
    using static Vue_Echarts.Mdl.Enum;

    public partial class Outpatient
    {
        public int OutpatientId { get; set; }
        public string PatientName { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string DiseaseCode { get; set; }
        public string DiseaseName { get; set; }
        public EOutpatient OutpatientType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUser { get; set; }
    }
}
